version: '3.3'
services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    image: mysql:5.7
  elasticsearch:
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '9200:3306'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1